language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - pipenv run pytest tests
  - pipenv run flake8 --ignore=E501,F401,E128,E402,E731,F821 whois
