name: dagger
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call Dagger workflow
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: .
          args: >-
            build-and-push
            --project-dir=.
            --git-ref=env:GITHUB_REF
            --git-commit=env:GITHUB_SHA
            --registry=ghcr.io
            --image-name=spotty-kiwi/whohacks
            --registry-user=env:GITHUB_ACTOR
            --registry-token=env:GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

