name: dagger
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call Dagger workflow
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: python helpers/build.py
