name: dagger
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call Dagger workflow
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: build-and-push
          args: >
            --git-ref=$GITHUB_REF
            --git-commit=$GITHUB_SHA
            --registry=ghcr.io
            --image-name=whohacks
            --registry-user=$GITHUB_ACTOR
            --registry-token=env:GITHUB_TOKEN

